import { expect, test } from '@playwright/test'

async function selectContents(page: Parameters<typeof test>[0]['page'], selector: string) {
  await page.locator(selector).evaluate(element => {
    const range = document.createRange()
    range.selectNodeContents(element)
    const selection = window.getSelection()!
    selection.removeAllRanges()
    selection.addRange(range)
  })
}

const primary = process.platform === 'darwin' ? 'Meta' : 'Control'

test.beforeEach(async ({ page }) => {
  await page.goto('/tests/browser/editor-fixture.html')
  await expect(page.locator('.editor-wysiwyg')).toBeVisible()
})

test('keeps typing in a new paragraph after a heading shortcut', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await editor.locator('p').click()
  await page.keyboard.press(`${primary}+3`)
  await expect(editor.locator('h3')).toHaveCount(1)
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await page.keyboard.type('body text')
  await expect(editor.locator('h3')).toHaveText('Body')
  await expect(editor.locator('h3 + p')).toHaveText('body text')
  await expect(page.locator('#markdown-output')).toContainText('### Body')
  await expect(page.locator('#markdown-output')).toContainText('body text')
})

test('supports ordered-list continuation without jumping while using a soft break', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await selectContents(page, '.editor-wysiwyg p')
  await page.getByTitle(/有序列表/).click()
  const item = editor.locator('ol > li').first()
  await item.click()
  await page.keyboard.press('End')
  await page.keyboard.press('Shift+Enter')
  await page.keyboard.type('body text')
  await expect(editor.locator('ol > li')).toHaveCount(1)
  await expect(item).toContainText('Body')
  await expect(item).toContainText('body text')
  await expect(page.locator('#markdown-output')).toContainText('body text')
})

test('removes a selected code block without leaving metadata or a divider', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await selectContents(page, '.editor-wysiwyg p')
  await page.getByTitle(/代码块 \/ 在代码块内点击可退出/).click()
  await editor.locator('code').click()
  await selectContents(page, 'pre code')
  await page.keyboard.press('Backspace')
  await expect(editor.locator('pre')).toHaveCount(0)
  await expect(editor.locator('.code-block-wrapper')).toHaveCount(0)
  await expect(editor.locator('.code-lang-label')).toHaveCount(0)
  await expect(editor.locator('[class*="code-language-history"]')).toHaveCount(0)
  await expect(page.locator('#markdown-output')).not.toContainText('```')
})

test('does not expose hljs as a code language after clearing language', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await selectContents(page, '.editor-wysiwyg p')
  await page.getByTitle(/代码块 \/ 在代码块内点击可退出/).click()
  await editor.locator('code').click()
  await page.getByTitle('代码块语言').click()
  const filter = page.locator('.lang-picker-input')
  await filter.fill('python')
  await page.getByRole('button', { name: /python/ }).click()
  await expect(editor.locator('pre')).toHaveAttribute('data-lang', 'python')
  await page.getByTitle('代码块语言').click()
  await filter.fill('')
  await page.getByRole('button', { name: /无语言|No language/ }).click()
  await expect(editor.locator('pre')).toHaveAttribute('data-lang', '')
  await expect(editor.locator('.code-lang-label')).toHaveCount(0)
  await expect(editor.locator('pre code')).not.toHaveClass(/language-hljs/)
  await expect(page.locator('#markdown-output')).toContainText('```\n')
})

test('undoes and redoes a visual table row insertion', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await editor.locator('p').click()
  await page.getByTitle('插入可视化表格').click()
  await editor.locator('table tbody td').first().click()
  await page.getByTitle('在下方添加一行').click()
  await expect(editor.locator('table tbody tr')).toHaveCount(3)
  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator('table tbody tr')).toHaveCount(2)
  await page.keyboard.press(`${primary}+Y`)
  await expect(editor.locator('table tbody tr')).toHaveCount(3)
})

test('does not leak code-language undo history between notes with identical text', async ({ page }) => {
  await page.getByTestId('load-identical-code-notes').click()
  const editor = page.locator('.editor-wysiwyg')
  await expect(editor.locator('pre')).toHaveAttribute('data-lang', '')
  await editor.locator('code').click()
  await page.getByTitle('代码块语言').click()
  await page.getByRole('button', { name: /^python$/ }).click()
  await expect(editor.locator('pre')).toHaveAttribute('data-lang', 'python')

  await page.getByTestId('switch-identical-note').click()
  await expect(page.getByTestId('active-note')).toHaveText('note-b')
  await expect(editor.locator('pre')).toHaveAttribute('data-lang', 'python')

  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator('pre')).toHaveAttribute('data-lang', 'python')
})

test('undoes and redoes a code language change', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await selectContents(page, '.editor-wysiwyg p')
  await page.getByTitle(/代码块 \/ 在代码块内点击可退出/).click()
  await editor.locator('code').click()
  await page.getByTitle('代码块语言').click()
  await page.getByRole('button', { name: /^python$/ }).click()
  await expect(editor.locator('pre')).toHaveAttribute('data-lang', 'python')
  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator('pre')).toHaveAttribute('data-lang', '')
  await page.keyboard.press(`${primary}+Y`)
  await expect(editor.locator('pre')).toHaveAttribute('data-lang', 'python')
})

test('undoes and redoes deleting a visual table', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await editor.locator('p').click()
  await page.getByTitle('插入可视化表格').click()
  await editor.locator('table tbody td').first().click()
  await page.getByTitle('删除表格').click()
  await expect(editor.locator('table')).toHaveCount(0)
  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator('table')).toHaveCount(1)
  await page.keyboard.press(`${primary}+Y`)
  await expect(editor.locator('table')).toHaveCount(0)
})

test('undoes and redoes visual table row and column deletion', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await editor.locator('p').click()
  await page.getByTitle('插入可视化表格').click()
  await editor.locator('table tbody td').first().click()

  await page.getByTitle('删除当前行').click()
  await expect(editor.locator('table tbody tr')).toHaveCount(1)
  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator('table tbody tr')).toHaveCount(2)
  await page.keyboard.press(`${primary}+Y`)
  await expect(editor.locator('table tbody tr')).toHaveCount(1)

  await editor.locator('table tbody td').first().click()
  await page.getByTitle('删除当前列').click()
  await expect(editor.locator('table tr').first().locator('th')).toHaveCount(2)
  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator('table tr').first().locator('th')).toHaveCount(3)
  await page.keyboard.press(`${primary}+Shift+Z`)
  await expect(editor.locator('table tr').first().locator('th')).toHaveCount(2)
})

test('clears visual-table history after editing in source mode', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await editor.locator('p').click()
  await page.getByTitle('插入可视化表格').click()
  await editor.locator('table tbody td').first().click()
  await page.getByTitle(/源代码/).click()
  const source = page.locator('.editor-source-textarea')
  await source.fill('# changed from source')
  await expect(source).toHaveValue('# changed from source')
  await page.getByTitle(/^编辑/).click()
  await expect(editor.locator('table')).toHaveCount(0)
  await expect(page.locator('#markdown-output')).toContainText('# changed from source')
})

test('exits an empty ordered-list item with Enter and continues in body text', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await selectContents(page, '.editor-wysiwyg p')
  await page.getByTitle(/有序列表/).click()
  const firstItem = editor.locator('ol > li').first()
  await firstItem.click()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await expect(editor.locator('ol > li')).toHaveCount(2)
  await page.keyboard.press('Enter')
  await page.keyboard.type('after list')

  await expect(editor.locator('ol > li')).toHaveCount(1)
  await expect(editor.locator('ol + p')).toContainText('after list')
  await expect(page.locator('#markdown-output')).toContainText('after list')
})

test('turns an empty list item into an editable paragraph with Backspace', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await selectContents(page, '.editor-wysiwyg p')
  await page.getByTitle(/有序列表/).click()
  await editor.locator('ol > li').first().click()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Backspace')
  await page.keyboard.type('body after list')

  await expect(editor.locator('ol > li')).toHaveCount(1)
  await expect(editor.locator('ol + p')).toContainText('body after list')
  await expect(page.locator('#markdown-output')).toContainText('body after list')
})

test('adds a visual-table row with Tab from the last cell and supports undo and redo', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await editor.locator('p').click()
  await page.getByTitle('插入可视化表格').click()
  const lastCell = editor.locator('table tbody td').last()
  await lastCell.click()
  await page.keyboard.press('End')
  await page.keyboard.press('Tab')
  await expect(editor.locator('table tbody tr')).toHaveCount(3)
  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator('table tbody tr')).toHaveCount(2)
  await page.keyboard.press(`${primary}+Y`)
  await expect(editor.locator('table tbody tr')).toHaveCount(3)
})

test('undoes ordinary typing before undoing the preceding visual-table action', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await editor.locator('p').click()
  await page.getByTitle('插入可视化表格').click()
  await editor.locator('table tbody td').first().click()
  await page.getByTitle('在下方添加一行').click()
  await expect(editor.locator('table tbody tr')).toHaveCount(3)

  const cell = editor.locator('table tbody td').first()
  await cell.click()
  await page.keyboard.insertText('typed')
  await expect(cell).toContainText('typed')

  await page.keyboard.press(`${primary}+Z`)
  await expect(cell).not.toContainText('typed')
  await expect(editor.locator('table tbody tr')).toHaveCount(3)
  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator('table tbody tr')).toHaveCount(2)
})

test('redoes ordinary typing after redoing the preceding visual-table action', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await editor.locator('p').click()
  await page.getByTitle('插入可视化表格').click()
  await editor.locator('table tbody td').first().click()
  await page.getByTitle('在下方添加一行').click()
  const cell = editor.locator('table tbody td').first()
  await cell.click()
  await page.keyboard.insertText('typed')

  await page.keyboard.press(`${primary}+Z`)
  await expect(cell).not.toContainText('typed')
  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator('table tbody tr')).toHaveCount(2)
  await page.keyboard.press(`${primary}+Y`)
  await expect(editor.locator('table tbody tr')).toHaveCount(3)
  await page.keyboard.press(`${primary}+Y`)
  await expect(editor.locator('table tbody td').first()).toContainText('typed')
})

test('undoes and redoes ordered-list formatting without invalid paragraph nesting', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await selectContents(page, '.editor-wysiwyg p')
  await page.getByTitle(/有序列表/).click()
  await expect(editor.locator(':scope > ol > li')).toHaveText('Body')
  await expect(editor.locator('p > ol, p > ul')).toHaveCount(0)

  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator(':scope > p')).toHaveText('Body')
  await expect(editor.locator(':scope > ol')).toHaveCount(0)
  await page.keyboard.press(`${primary}+Y`)
  await expect(editor.locator(':scope > ol > li')).toHaveText('Body')
  await expect(editor.locator('p > ol, p > ul')).toHaveCount(0)
})

test('keeps nested ordered-list indentation valid through Tab and Shift+Tab', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await selectContents(page, '.editor-wysiwyg p')
  await page.getByTitle(/有序列表/).click()
  await editor.locator('ol > li').first().click()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await page.keyboard.insertText('Nested')
  await page.keyboard.press('Tab')
  await expect(editor.locator(':scope > ol > li > ol > li')).toHaveText('Nested')
  await expect(editor.locator('p > ol, p > ul')).toHaveCount(0)

  await page.keyboard.press('Shift+Tab')
  await expect(editor.locator(':scope > ol > li')).toHaveCount(2)
  await expect(editor.locator('p > ol, p > ul')).toHaveCount(0)
})

test('supports code-block newlines and exits with the primary Enter shortcut', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await selectContents(page, '.editor-wysiwyg p')
  await page.getByTitle(/代码块 \/ 在代码块内点击可退出/).click()
  const code = editor.locator('pre code')
  await code.click()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await page.keyboard.insertText('second line')
  await expect(code).toContainText('Body\nsecond line')

  await page.keyboard.press(`${primary}+Enter`)
  await page.keyboard.insertText('after code')
  await expect(editor.locator('.code-block-wrapper + p')).toContainText('after code')
  await expect(page.locator('#markdown-output')).toContainText('second line')
  await expect(page.locator('#markdown-output')).toContainText('after code')
})

test('does not add a visual-table row when Shift+Tab is pressed in the first cell', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await editor.locator('p').click()
  await page.getByTitle('插入可视化表格').click()
  const firstCell = editor.locator('table thead th').first()
  await firstCell.click()
  await page.keyboard.press('Shift+Tab')
  await expect(editor.locator('table tbody tr')).toHaveCount(2)
})

test('undoes and redoes consecutive rows added by Tab from the last table cell', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await editor.locator('p').click()
  await page.getByTitle('插入可视化表格').click()
  for (const expectedRows of [3, 4]) {
    const lastCell = editor.locator('table tbody td').last()
    await lastCell.click()
    await page.keyboard.press('End')
    await page.keyboard.press('Tab')
    await expect(editor.locator('table tbody tr')).toHaveCount(expectedRows)
  }
  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator('table tbody tr')).toHaveCount(3)
  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator('table tbody tr')).toHaveCount(2)
  await page.keyboard.press(`${primary}+Y`)
  await expect(editor.locator('table tbody tr')).toHaveCount(3)
  await page.keyboard.press(`${primary}+Y`)
  await expect(editor.locator('table tbody tr')).toHaveCount(4)
})

test('undoes and redoes exiting an empty ordered-list item', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await selectContents(page, '.editor-wysiwyg p')
  await page.getByTitle(/有序列表/).click()
  await editor.locator('ol > li').first().click()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Enter')
  await expect(editor.locator(':scope > ol > li')).toHaveCount(1)
  await expect(editor.locator(':scope > ol + p')).toHaveCount(1)

  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator(':scope > ol > li')).toHaveCount(2)
  await page.keyboard.press(`${primary}+Y`)
  await expect(editor.locator(':scope > ol > li')).toHaveCount(1)
  await expect(editor.locator(':scope > ol + p')).toHaveCount(1)
})

test('undoes and redoes a code-block newline without splitting the code element', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await selectContents(page, '.editor-wysiwyg p')
  await page.getByTitle(/代码块 \/ 在代码块内点击可退出/).click()
  const code = editor.locator('pre code')
  await code.click()
  await page.keyboard.press('End')
  await page.keyboard.press('Enter')
  await expect(editor.locator('pre code')).toHaveCount(1)
  await expect(page.locator('#markdown-output')).toHaveText('```\nBody\n```\n')
  await page.keyboard.press(`${primary}+Z`)
  await expect(editor.locator('pre code')).toHaveText('Body')
  await page.keyboard.press(`${primary}+Y`)
  await expect(editor.locator('pre code')).toHaveCount(1)
  await expect(editor.locator('pre code')).toHaveText('Body\n')
})

test('undoes and redoes multiple code-language changes including no language', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await selectContents(page, '.editor-wysiwyg p')
  await page.getByTitle(/代码块 \/ 在代码块内点击可退出/).click()
  const pre = editor.locator('pre')
  await editor.locator('code').click()
  for (const language of ['python', 'javascript']) {
    await page.getByTitle('代码块语言').click()
    await page.locator('.lang-picker-input').fill(language)
    await page.getByRole('button', { name: new RegExp(`^${language}$`) }).click()
  }
  await page.getByTitle('代码块语言').click()
  await page.locator('.lang-picker-input').fill('')
  await page.getByRole('button', { name: /无语言|No language/ }).click()
  await expect(pre).toHaveAttribute('data-lang', '')

  await page.keyboard.press(`${primary}+Z`)
  await expect(pre).toHaveAttribute('data-lang', 'javascript')
  await page.keyboard.press(`${primary}+Z`)
  await expect(pre).toHaveAttribute('data-lang', 'python')
  await page.keyboard.press(`${primary}+Z`)
  await expect(pre).toHaveAttribute('data-lang', '')
  await page.keyboard.press(`${primary}+Y`)
  await expect(pre).toHaveAttribute('data-lang', 'python')
  await page.keyboard.press(`${primary}+Y`)
  await expect(pre).toHaveAttribute('data-lang', 'javascript')
  await page.keyboard.press(`${primary}+Y`)
  await expect(pre).toHaveAttribute('data-lang', '')
})

test('undoes consecutive visual-table alignment changes in order', async ({ page }) => {
  const editor = page.locator('.editor-wysiwyg')
  await editor.locator('p').click()
  await page.getByTitle('插入可视化表格').click()
  await editor.locator('table tbody td').first().click()
  const firstHeader = editor.locator('table thead th').first()
  await page.getByTitle('当前列居中').click()
  await expect(firstHeader).toHaveAttribute('align', 'center')
  await page.getByTitle('当前列右对齐').click()
  await expect(firstHeader).toHaveAttribute('align', 'right')
  await page.keyboard.press(`${primary}+Z`)
  await expect(firstHeader).toHaveAttribute('align', 'center')
  await page.keyboard.press(`${primary}+Z`)
  await expect(firstHeader).not.toHaveAttribute('align', /.+/)
  await page.keyboard.press(`${primary}+Y`)
  await expect(firstHeader).toHaveAttribute('align', 'center')
  await page.keyboard.press(`${primary}+Y`)
  await expect(firstHeader).toHaveAttribute('align', 'right')
})
